package com.example.william.my.module.database.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.william.my.module.database.greendao.GreendaoNote;

import com.example.william.my.module.database.greendao.dao.GreendaoNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greendaoNoteDaoConfig;

    private final GreendaoNoteDao greendaoNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greendaoNoteDaoConfig = daoConfigMap.get(GreendaoNoteDao.class).clone();
        greendaoNoteDaoConfig.initIdentityScope(type);

        greendaoNoteDao = new GreendaoNoteDao(greendaoNoteDaoConfig, this);

        registerDao(GreendaoNote.class, greendaoNoteDao);
    }
    
    public void clear() {
        greendaoNoteDaoConfig.clearIdentityScope();
    }

    public GreendaoNoteDao getGreendaoNoteDao() {
        return greendaoNoteDao;
    }

}
